site_name: textual-tty
repo_url: https://github.com/ttygroup/textual-tty
theme:
  name: material
  palette:
    primary: 'indigo'
    accent: 'blue'
  features:
    - navigation.expand_single_toc_entry
    - navigation.sections
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
 - 'index.md'
 - 'LICENSE.md'
 - 'pydoc/index.md'
