#!/bin/bash

BLUE="\033[1;48;5;17;37m"
DARK="\033[1;38;5;240m"
INVERT="\033[1;48;5;248;38;5;17m"
OFF="\033[0m"

echo -e "$BLUE                                                                                $OFF"
echo -e "$BLUE                                                                                $OFF"
echo -e "$BLUE                                                                                $OFF"
echo -e "$BLUE                                                                                $OFF"
echo -e "$BLUE                                                                                $OFF"
echo -e "$BLUE                                                                                $OFF"
echo -e "$BLUE                                                                                $OFF"
echo -e "$BLUE                                                                                $OFF"
echo -e "$BLUE                                                                                $OFF"
echo -e "$BLUE                                  $INVERT Windows $BLUE                                     $OFF"
echo -e "$BLUE                                                                                $OFF"
echo -e "$BLUE    An error has occured. To continue:                                          $OFF"
echo -e "$BLUE                                                                                $OFF"
echo -e "$BLUE    Press Enter to return to Windows, or                                        $OFF"
echo -e "$BLUE                                                                                $OFF"
echo -e "$BLUE                                                                                $OFF"
echo -e "$BLUE    Press CTRL+ALT+DEL to restart your computer. If you do this,                $OFF"
echo -e "$BLUE    you will lose any unsaved information in all open applications.             $OFF"
echo -e "$BLUE                                                                                $OFF"
echo -e "$BLUE    Error: 0E : 016F : DEADBEEF                                                 $OFF"
echo -e "$BLUE                                                                                $OFF"
echo -e "$BLUE                          Press any key to continue ${DARK}_${BLUE}                           $OFF"
echo -e "$BLUE                                                                                $OFF"
echo -e "$BLUE                                                                                $OFF"
echo -e "$BLUE                                                                                $OFF"
echo -e "$BLUE                                                                                $OFF"
echo -e "$BLUE                                                                                $OFF"
echo -e "$BLUE                                                                                $OFF"
