#!/bin/bash

BLUE="\033[1;48;5;17;37m"
DARK="\033[1;38;5;240m"
INVERT="\033[1;48;5;248;38;5;17m"
OFF="\033[0m"

echo -e "$BLUE                                                                                $OFF"
echo -e "$BLUE                                                                                $OFF"
echo -e "$BLUE                                                                                $OFF"
echo -e "$BLUE                                                                                $OFF"
echo -e "$BLUE                                                                                $OFF"
echo -e "$BLUE                                                                                $OFF"
echo -e "$BLUE                                                                                $OFF"
echo -e "$BLUE                                                                                $OFF"
echo -e "$BLUE                                                                                $OFF"
echo -e "$BLUE                                  $INVERT Windows $BLUE                                     $OFF"
echo -e "$BLUE                                                                                $OFF"
echo -e "$BLUE    Although you can use CTRL+ALT+DEL to quit an application that has           $OFF"
echo -e "$BLUE    stopped responding to the system, there is no application in this           $OFF"
echo -e "$BLUE    state.                                                                      $OFF"
echo -e "$BLUE                                                                                $OFF"
echo -e "$BLUE    To quit an application, use the application's quit or exit command,         $OFF"
echo -e "$BLUE    or choose Close from the Control menu.                                      $OFF"
echo -e "$BLUE                                                                                $OFF"
echo -e "$BLUE    *  Press any key to return to Windows.                                      $OFF"
echo -e "$BLUE    *  Press CTRL+ALT+DEL to restart your computer. You will                    $OFF"
echo -e "$BLUE       lose any unsaved information in all applications.                        $OFF"
echo -e "$BLUE                                                                                $OFF"
echo -e "$BLUE                          Press any key to continue ${DARK}_${BLUE}                           $OFF"
echo -e "$BLUE                                                                                $OFF"
echo -e "$BLUE                                                                                $OFF"
echo -e "$BLUE                                                                                $OFF"
echo -e "$BLUE                                                                                $OFF"
echo -e "$BLUE                                                                                $OFF"
